server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**, /api/v1/categories/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory/**
        - id: prescription-service
          uri: lb://prescription-service
          predicates:
            - Path=/api/v1/prescriptions/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/api/v1/files/**
        - id: loyalty-service
          uri: lb://loyalty-service
          predicates:
            - Path=/api/v1/loyalty/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s
        pool:
          type: elastic
          max-idle-time: 30s
    loadbalancer:
      retry:
        enabled: true
      cache:
        enabled: true
        ttl: 10s

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"
